name: Manage labels

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.0.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          exclude: |
            help*
            *issue
